services:
  bank_a_validator_1:
    image: hyperledger/besu:latest
    container_name: thesis-bank-a-validator-1
    command: ["--config-file=/network/nodes/bank-a-validator-1/config.toml"]
    volumes:
      - ./networks/besu/chainA:/network
    ports:
      - "8545:8545"
    networks:
      thesis_besu:
        ipv4_address: 172.30.10.11
  bank_a_validator_2:
    image: hyperledger/besu:latest
    container_name: thesis-bank-a-validator-2
    command: ["--config-file=/network/nodes/bank-a-validator-2/config.toml"]
    volumes:
      - ./networks/besu/chainA:/network
    networks:
      thesis_besu:
        ipv4_address: 172.30.10.12
  bank_a_validator_3:
    image: hyperledger/besu:latest
    container_name: thesis-bank-a-validator-3
    command: ["--config-file=/network/nodes/bank-a-validator-3/config.toml"]
    volumes:
      - ./networks/besu/chainA:/network
    networks:
      thesis_besu:
        ipv4_address: 172.30.10.13
  bank_a_validator_4:
    image: hyperledger/besu:latest
    container_name: thesis-bank-a-validator-4
    command: ["--config-file=/network/nodes/bank-a-validator-4/config.toml"]
    volumes:
      - ./networks/besu/chainA:/network
    networks:
      thesis_besu:
        ipv4_address: 172.30.10.14
  bank_b_validator_1:
    image: hyperledger/besu:latest
    container_name: thesis-bank-b-validator-1
    command: ["--config-file=/network/nodes/bank-b-validator-1/config.toml"]
    volumes:
      - ./networks/besu/chainB:/network
    ports:
      - "9545:8545"
    networks:
      thesis_besu:
        ipv4_address: 172.30.20.11
  bank_b_validator_2:
    image: hyperledger/besu:latest
    container_name: thesis-bank-b-validator-2
    command: ["--config-file=/network/nodes/bank-b-validator-2/config.toml"]
    volumes:
      - ./networks/besu/chainB:/network
    networks:
      thesis_besu:
        ipv4_address: 172.30.20.12
  bank_b_validator_3:
    image: hyperledger/besu:latest
    container_name: thesis-bank-b-validator-3
    command: ["--config-file=/network/nodes/bank-b-validator-3/config.toml"]
    volumes:
      - ./networks/besu/chainB:/network
    networks:
      thesis_besu:
        ipv4_address: 172.30.20.13
  bank_b_validator_4:
    image: hyperledger/besu:latest
    container_name: thesis-bank-b-validator-4
    command: ["--config-file=/network/nodes/bank-b-validator-4/config.toml"]
    volumes:
      - ./networks/besu/chainB:/network
    networks:
      thesis_besu:
        ipv4_address: 172.30.20.14
networks:
  thesis_besu:
    driver: bridge
    ipam:
      config:
        - subnet: "172.30.0.0/16"
