data-path="/network/nodes/bank-a-validator-1/data"
genesis-file="/network/genesis.json"
node-private-key-file="/network/nodes/bank-a-validator-1/key"
static-nodes-file="/network/nodes/bank-a-validator-1/static-nodes.json"
p2p-host="0.0.0.0"
p2p-port=30303
discovery-enabled=false
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-api=["ETH","NET","WEB3","QBFT","ADMIN","DEBUG"]
rpc-http-cors-origins=["all"]
host-allowlist=["*"]
rpc-ws-enabled=false
min-gas-price=0
sync-mode="FULL"
sync-min-peers=0
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9546
logging="INFO"
identity="chainA-bank-a-validator-1"
