export const statusFixture = Object.freeze({
  ready: true,
  runtimeReadable: true,
  chainsProgressing: true,
  attestorQuorumReady: true,
  relayerHealthy: true,
  governanceEnforced: true,
  identitiesEligible: true,
  laneReady: true,
  deployed: true,
  stackVersion: "institutional-v1",
  generatedAt: "2026-08-02T00:00:00.000Z",
  message: null,
  controller: { busy: false, activeOperation: null },
  topology: {
    validatorsPerChain: 4,
    toleratedFaultsPerChain: 1,
    checkpointModel: "attestor-quorum",
    attestorThreshold: 3,
    configuredAttestors: 4,
    finalityDepth: 2,
  },
  governance: {
    mode: "timelock-enforced",
    delaySeconds: { A: "60", B: "60" },
  },
  chains: {
    A: { chainId: "41001", blockNumber: 12840, trustedRemoteHeight: 12794 },
    B: { chainId: "41002", blockNumber: 12796, trustedRemoteHeight: 12838 },
  },
  participants: {
    sourceCustomer: "0xA1000000000000000000000000000000000000A1",
    destinationCustomer: "0xB1000000000000000000000000000000000000B1",
    relayerA: "0xA2000000000000000000000000000000000000A2",
    relayerB: "0xB2000000000000000000000000000000000000B2",
    identity: {
      A: { active: true, label: "active" },
      B: { active: true, label: "active" },
    },
  },
  balances: {
    canonicalAvailable: "98500",
    escrowed: "1000",
    voucherAvailable: "400",
    creditAvailable: "1200",
    activeCollateral: "600",
    outstandingDebt: "200",
    poolLiquidity: "999800",
    totalBorrows: "200",
  },
  risk: {
    maxBorrow: "420",
    maxBorrowRaw: "420000000000000000000",
    availableBorrow: "220",
    availableBorrowRaw: "220000000000000000000",
    collateralValue: "600",
    liquidationThresholdValue: "480",
    healthFactor: "2.4",
    collateralFactorBps: "7000",
    liquidationThresholdBps: "8000",
    voucherPrice: "1",
    debtPrice: "1",
    voucherPriceUpdatedAt: "1785628800",
    debtPriceUpdatedAt: "1785628800",
    originationPrincipalDebt: "200",
    accountDefaulted: false,
    creditStatus: "eligible",
    pausedActionMask: "0",
    borrowPaused: false,
    collateralWithdrawalPaused: false,
    accrualBacklogSeconds: "0",
    accrualBatchesRequired: "0",
    accrualCatchUpRequired: false,
  },
  relay: {
    activeAttestors: 4,
    completedMessages: 12,
    pendingMessages: 0,
    latestJob: null,
  },
  gateway: { nextNonceA: "13", nextNonceB: "1" },
  workflow: { stage: "manage", nextAction: "repay" },
  activity: {
    latest: {
      action: "borrow",
      label: "Borrow bCASH",
      lane: "Bank B",
      status: "completed",
      sourceTransaction: "0xc300000000000000000000000000000000000000000000000000000000000003",
      finishedAt: "2026-08-02T00:00:03.000Z",
    },
    history: [
      {
        action: "borrow",
        label: "Borrow bCASH",
        lane: "Bank B",
        status: "completed",
        sourceTransaction: "0xc300000000000000000000000000000000000000000000000000000000000003",
        finishedAt: "2026-08-02T00:00:03.000Z",
      },
      {
        action: "deposit",
        label: "Activate collateral",
        lane: "Bank B",
        status: "completed",
        sourceTransaction: "0xc200000000000000000000000000000000000000000000000000000000000002",
        finishedAt: "2026-08-02T00:00:02.000Z",
      },
      {
        action: "bridge",
        label: "Lock aBANK and issue vA",
        lane: "Bank A → Bank B",
        status: "completed",
        messageId: "0xc100000000000000000000000000000000000000000000000000000000000001",
        finishedAt: "2026-08-02T00:00:01.000Z",
      },
    ],
  },
});

export const evidenceFixture = Object.freeze({
  available: true,
  status: "passed",
  reportStatus: "passed",
  applicableToCurrentSource: true,
  applicabilityReason: "matched",
  validatorRuntime: {
    schema: "institutional-evidence-validator-runtime-v1",
    loadedCommitShort: "7e57c0de",
    currentCommitShort: "7e57c0de",
    sourceMatchesCurrent: true,
    reason: "matched",
  },
  generatedAt: "2026-08-02T00:10:00.000Z",
  provenance: {
    sourceMatches: true,
    recordedCommitShort: "7e57c0de",
  },
  benchmark: {
    sampleCount: 12,
    postSourceInclusionToCompletionP95Ms: 1840,
    targetP95Ms: 3000,
    endToEndP95Ms: 2310,
  },
  integration: {
    status: "passed",
    passed: 5,
    total: 5,
    tests: [
      { id: "lockMint", title: "Lock and mint", status: "passed" },
      { id: "lending", title: "Policy-controlled lending", status: "passed" },
      { id: "burnUnlock", title: "Burn and unlock", status: "passed" },
      { id: "quorumOutage", title: "Attestor quorum outage", status: "passed" },
      { id: "engineReloadRecovery", title: "Relay engine reload recovery", status: "passed" },
    ],
  },
  security: {
    status: "passed",
    passed: 14,
    total: 14,
    scenarios: [
      {
        id: "SEC-01",
        title: "Insufficient checkpoint quorum",
        control: "A checkpoint with fewer than three of four configured attestors is rejected.",
        status: "passed",
      },
      {
        id: "SEC-02",
        title: "Replay or forged commitment",
        control: "The gateway rejects both duplicate receipt execution and a commitment that differs from proven storage.",
        status: "passed",
      },
      {
        id: "SEC-03",
        title: "Suspended institutional identity",
        control: "Suspended customers cannot originate or receive institutional collateral messages.",
        status: "passed",
      },
      {
        id: "SEC-04",
        title: "Origination-principal cap violation",
        control: "One aggregate account origination-principal cap rejects excessive new principal across debt assets.",
        status: "passed",
      },
      {
        id: "SEC-05",
        title: "Direct governance bypass",
        control: "Sensitive administration cannot bypass the timelock after governance handoff.",
        status: "passed",
      },
      {
        id: "SEC-06",
        title: "Duplicate business request",
        control: "A sender cannot reuse a client reference to lock or burn collateral twice.",
        status: "passed",
      },
      {
        id: "SEC-07",
        title: "Debt conservation under full repayment",
        control: "Fuzzed full repayments clear debt only when pool cash increases by the same amount.",
        status: "passed",
      },
      {
        id: "SEC-08",
        title: "Emergency pause with in-flight timeout",
        control: "Pause blocks new risk but still permits a proof-checked terminal timeout.",
        status: "passed",
      },
      {
        id: "SEC-09",
        title: "Compliance hold during compensation",
        control: "A suspended sender's refund remains atomically pending and succeeds only after compliance resolution.",
        status: "passed",
      },
      {
        id: "SEC-10",
        title: "Unauthorized voucher transfer",
        control: "Collateral receipts cannot move wallet-to-wallet outside an approved institutional operator.",
        status: "passed",
      },
      {
        id: "SEC-11",
        title: "Revoked credential reactivation",
        control: "Revocation is terminal and cannot be converted back to an active credential.",
        status: "passed",
      },
      {
        id: "SEC-12",
        title: "Checkpoint recovery authorization floor",
        control: "Recovery preserves historical root data but rejects proof authorization below the recovery floor.",
        status: "passed",
      },
      {
        id: "SEC-13",
        title: "Revoked lock-timeout restitution",
        control: "Canonical compensation for a terminally revoked sender enters accounted restricted custody.",
        status: "passed",
      },
      {
        id: "SEC-14",
        title: "Revoked burn-timeout restitution",
        control: "Voucher compensation for a terminally revoked sender enters accounted restricted custody.",
        status: "passed",
      },
    ],
  },
});

export const staleValidatorEvidenceFixture = Object.freeze({
  ...evidenceFixture,
  status: "validator-stale",
  reportStatus: "failed",
  validatorRuntime: Object.freeze({
    schema: "institutional-evidence-validator-runtime-v1",
    loadedCommitShort: "11111111",
    currentCommitShort: "22222222",
    sourceMatchesCurrent: false,
    reason: "commit-mismatch",
  }),
  validation: Object.freeze({
    failedGates: Object.freeze(["security-profile", "component-reports"]),
    totalGates: 19,
  }),
});
